language: python
python:
- 2.7
- 3.6

before_install:
  - sudo apt-get install libimage-exiftool-perl

install:
  - python setup.py install
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script:
  - nosetests tests
